# Generated by Django 5.1.5 on 2025-02-05 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='slag',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='slag',
            new_name='slug',
        ),
    ]
